--- #YAML:1.0
name:                Object-Tiny-XS
version:             1.00
abstract:            Class building as simple as it gets and FAST
license:             perl
author:              
    - Steffen Mueller <smueller@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::XSAccessor:             0.11
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
